 

import '@/assets/fonts/fonts.css'
import "./globals.css";
import MainLayout from "@/layout/MainLayout";
import NextTopLoader from 'nextjs-toploader';

 

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` font-pregular bg-whitesmoke`}
      >
        <MainLayout>
        <NextTopLoader color='#21004b' />
        {children}
        </MainLayout>
      </body>
    </html>
  );
}
